MySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('content.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns +=[
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        })
    ]

content/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.views.static import serve

app_name = "MySite"
urlpatterns = [
    path('', views.home, name="home"),
    path('essay/', views.essayIndex, name="essayIndex"),
    path('essay/<str:title>/', views.essay, name="essay"),
]

content/models.py
from django.db import models

class Essay(models.Model):
    title = models.CharField(max_length=50, primary_key=True)
    essay = models.FileField(upload_to="essays", blank=True, null=True)
    pub_date = models.DateField(blank=True, null=True)

content/views.py
from django.shortcuts import get_object_or_404, render
from .models import Essay

essayList = Essay.objects.order_by('-pub_date'[0:])

def home(request):
   latest_essays = essayList[:5]

   essay_url = Essay.essay
   context = {"latest_essays": latest_essays,
              "essay_url": essay_url,

              }
   return render(request, "content/home.html", context)

def essay(request, title):
        essay = get_object_or_404(Essay, pk=title)
        title = essay.title
        text = essay.essay.read()
        text = str(text)
        text = text[1:] #gets rid of bytes
        context = {"title": title,
                   "text": text,
        }
        return render(request, "content/essay.html", context)


def essayIndex(request):
    context = {"essayList" : essayList}
    return render(request,"content/essay_index.html", context)

# make the text for the body not red

content/templates/content/base.html
<!DOCTYPE html>
<title>Base</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'content/basestyle.css'%}">
<body>
<div style="max-width:1600px">
  <header>
    <h1><b>Corey's Corner</b></h1>
    <h5>Welcome To My Corner Of The Internet</h5>
  </header>

    <div class="banner" >
      <a href="{% url "MySite:home" %}" >Home</a>
      <a href="{% url "MySite:essayIndex" %}" >Essays</a>
        <a href="https://podcasts.apple.com/us/podcast/coreys-corner/id1479097455">Podcast</a>
         <a href="https://www.youtube.com/channel/UCaLrLQ2w81iybR0o9eHlh4w">Youtube</a>
    </div>
<div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</div>

content/templates/content/essay.html
{% extends "content/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block content %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'content/essaystyle.css'%}">
        <h5 class="title">{{ title }}</h5>
        <p class="text">{{ text }}</p>
    {% endblock %}
</body>
</html>

content/templates/content/essay_index.html
{% extends  "content/base.html"%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Essay Index</title>
</head>
<body>
{% block content %}
    {% for essay in essayList %}
        <h2><a href="{% url 'MySite:essay' essay.title %}">{{ essay.title }} {{ essay.pub_date }}</a>
        </h2>
    {% endfor %}
{% endblock %}
</body>
</html>

content/templates/content/home.html
{% extends  "content/base.html"%}
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
{% block content %}
    {% for essay in latest_essays %}
        <h2><a href="{% url 'MySite:essay' essay.title %}">{{ essay.title }} </a></h2>
    {% endfor %}
{% endblock %}